-- MySQL Script generated by MySQL Workbench
-- Sun May  5 18:48:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cemetaryDB2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cemetaryDB2` ;

-- -----------------------------------------------------
-- Schema cemetaryDB2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cemetaryDB2` DEFAULT CHARACTER SET utf8 ;
USE `cemetaryDB2` ;

-- -----------------------------------------------------
-- Table `cemetaryDB2`.`tblMaterial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cemetaryDB2`.`tblMaterial` ;

CREATE TABLE IF NOT EXISTS `cemetaryDB2`.`tblMaterial` (
  `materialID` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(20) NULL,
  PRIMARY KEY (`materialID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cemetaryDB2`.`tblLocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cemetaryDB2`.`tblLocation` ;

CREATE TABLE IF NOT EXISTS `cemetaryDB2`.`tblLocation` (
  `locationID` INT NOT NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`locationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cemetaryDB2`.`tblGrave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cemetaryDB2`.`tblGrave` ;

CREATE TABLE IF NOT EXISTS `cemetaryDB2`.`tblGrave` (
  `graveID` INT NOT NULL AUTO_INCREMENT,
  `materialID` INT NOT NULL,
  `locationID` INT NULL,
  `size` VARCHAR (1),
  `adornment` VARCHAR (1),
  `adornmentdesc` VARCHAR (45) NULL,
  PRIMARY KEY (`graveID`),
  INDEX `fk_tblGrave_tblMaterial_idx` (`materialID` ASC) VISIBLE,
  INDEX `fk_tblGrave_tblLocation1_idx` (`locationID` ASC) VISIBLE,
  CONSTRAINT `fk_tblGrave_tblMaterial`
    FOREIGN KEY (`materialID`)
    REFERENCES `cemetaryDB2`.`tblMaterial` (`materialID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblGrave_tblLocation1`
    FOREIGN KEY (`locationID`)
    REFERENCES `cemetaryDB2`.`tblLocation` (`locationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cemetaryDB2`.`tblCorpse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cemetaryDB2`.`tblCorpse` ;

CREATE TABLE IF NOT EXISTS `cemetaryDB2`.`tblCorpse` (
  `corpseID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(20) NULL,
  `lastName` VARCHAR(20) NULL,
  `relationOne` VARCHAR(45) NULL,
  `relationTwo` VARCHAR(45) NULL,
  `relationThree` VARCHAR(45) NULL,
  `VeteranStatus` VARCHAR(3) BINARY NOT NULL DEFAULT 'No',
  `gender` VARCHAR(1) BINARY NULL,
  `birthYear` int(4) NULL,
  `deathYear` int(4) NULL,
  `age` INT NULL,
  PRIMARY KEY (`corpseID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cemetaryDB2`.`tblGraveCorpse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cemetaryDB2`.`tblGraveCorpse` ;

CREATE TABLE IF NOT EXISTS `cemetaryDB2`.`tblGraveCorpse` (
  `corpseID` INT NOT NULL,
  `graveID` INT NOT NULL,
  PRIMARY KEY (`corpseID`, `graveID`),
  INDEX `fk_tblGraveCorpse_tblGrave1_idx` (`graveID` ASC) VISIBLE,
  CONSTRAINT `fk_tblGraveCorpse_tblGrave1`
    FOREIGN KEY (`graveID`)
    REFERENCES `cemetaryDB2`.`tblGrave` (`graveID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblGraveCorpse_tblCorpse1`
    FOREIGN KEY (`corpseID`)
    REFERENCES `cemetaryDB2`.`tblCorpse` (`corpseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cemetaryDB2`.`tblWar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cemetaryDB2`.`tblWar` ;

CREATE TABLE IF NOT EXISTS `cemetaryDB2`.`tblWar` (
  `warID` INT NOT NULL,
  `warDescription` VARCHAR(45) NULL,
  PRIMARY KEY (`warID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cemetaryDB2`.`tblCorpseWar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cemetaryDB2`.`tblCorpseWar` ;

CREATE TABLE IF NOT EXISTS `cemetaryDB2`.`tblCorpseWar` (
  `corpseID` INT NOT NULL,
  `warID` INT NOT NULL,
  PRIMARY KEY (`corpseID`, `warID`),
  INDEX `fk_tblCorpseWar_tblWar1_idx` (`warID` ASC) VISIBLE,
  CONSTRAINT `fk_tblCorpseWar_tblCorpse1`
    FOREIGN KEY (`corpseID`)
    REFERENCES `cemetaryDB2`.`tblCorpse` (`corpseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblCorpseWar_tblWar1`
    FOREIGN KEY (`warID`)
    REFERENCES `cemetaryDB2`.`tblWar` (`warID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
