use cemetaryDB2;

INSERT INTO tbllocation VALUES(1, 'South');
INSERT INTO tbllocation VALUES(2, 'Fenced');
INSERT INTO tbllocation VALUES(3, 'North');

SELECT * FROM tbllocation;

INSERT INTO tblMaterial VALUES(	1,	'Limestone'	);
INSERT INTO tblMaterial VALUES(	2,	'Sandstone'	);
INSERT INTO tblMaterial VALUES(	3,	'Granite'	);
INSERT INTO tblMaterial VALUES(	4,	'Marble'	);
INSERT INTO tblMaterial VALUES(	5,	'Slate'	);
INSERT INTO tblMaterial VALUES(	6,	'Rock'	);

SELECT * FROM tblMaterial;

INSERT INTO tblGrave VALUES(	1	,	5	,	1	,	'L'	,	'Y'	,	'Name w/ banner'	);
INSERT INTO tblGrave VALUES(	2	,	2	,	1	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	3	,	5	,	1	,	'L'	,	'Y'	,	'Hand w/ Pointer finger up'	);
INSERT INTO tblGrave VALUES(	4	,	2	,	1	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	5	,	3	,	1	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	6	,	4	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	7	,	4	,	1	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	8	,	5	,	1	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	9	,	2	,	1	,	'L'	,	'Y'	,	'Window with Hole '	);
INSERT INTO tblGrave VALUES(	10	,	1	,	1	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	11	,	2	,	1	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	12	,	5	,	1	,	'L'	,	'Y'	,	'Hand w/ Pointer finger up'	);
INSERT INTO tblGrave VALUES(	13	,	2	,	1	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	14	,	2	,	1	,	'M'	,	'Y'	,	'Name w/ banner'	);
INSERT INTO tblGrave VALUES(	15	,	4	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	16	,	2	,	1	,	'L'	,	'Y'	,	'Name w/ banner'	);
INSERT INTO tblGrave VALUES(	17	,	5	,	1	,	'L'	,	'Y'	,	'Name w/ banner'	);
INSERT INTO tblGrave VALUES(	18	,	4	,	1	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	19	,	4	,	1	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	20	,	3	,	1	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	21	,	2	,	1	,	'S'	,	'Y'	,	'Name w/ banner'	);
INSERT INTO tblGrave VALUES(	22	,	5	,	1	,	'S'	,	'Y'	,	'Last Name in Rectangle'	);
INSERT INTO tblGrave VALUES(	23	,	3	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	24	,	4	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	25	,	4	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	26	,	2	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	27	,	2	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	28	,	2	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	29	,	4	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	30	,	2	,	3	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	31	,	2	,	3	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	32	,	2	,	3	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	33	,	4	,	3	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	34	,	4	,	3	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	35	,	2	,	3	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	36	,	4	,	3	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	37	,	4	,	3	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	38	,	4	,	3	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	39	,	1	,	3	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	40	,	1	,	3	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	41	,	1	,	3	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	42	,	1	,	3	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	43	,	2	,	3	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	44	,	5	,	3	,	'S'	,	'Y'	,	'Sunflower'	);
INSERT INTO tblGrave VALUES(	45	,	1	,	3	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	46	,	1	,	3	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	47	,	1	,	2	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	48	,	2	,	2	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	49	,	1	,	2	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	50	,	2	,	2	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	51	,	1	,	2	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	52	,	1	,	2	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	53	,	1	,	2	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	54	,	1	,	2	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	55	,	1	,	2	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	56	,	1	,	2	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	57	,	1	,	2	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	58	,	1	,	2	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	59	,	1	,	2	,	'S'	,	'Y'	,	'Candle'	);
INSERT INTO tblGrave VALUES(	60	,	1	,	2	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	61	,	1	,	2	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	62	,	1	,	2	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	63	,	6	,	2	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	64	,	6	,	2	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	65	,	1	,	2	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	66	,	6	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	67	,	6	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	68	,	6	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	69	,	6	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	70	,	6	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	71	,	6	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	72	,	6	,	1	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	73	,	1	,	1	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	74	,	1	,	1	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	75	,	1	,	1	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	76	,	6	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	77	,	6	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	78	,	6	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	79	,	1	,	1	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	80	,	6	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	81	,	6	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	82	,	1	,	1	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	83	,	1	,	1	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	84	,	1	,	1	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	85	,	1	,	1	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	86	,	1	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	87	,	1	,	1	,	'S'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	88	,	1	,	1	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	89	,	1	,	1	,	'M'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	90	,	1	,	1	,	'L'	,	'N'	,	""	);
INSERT INTO tblGrave VALUES(	91	,	1	,	1	,	'L'	,	'Y'	,	'American Flag'	);
INSERT INTO tblGrave VALUES(	92	,	1	,	1	,	'L'	,	'N'	,	'American Flag'	);



INSERT INTO tblCorpse VALUES(	101	,	'Aldrich'	,	'Mowry'	,	'Son of Daniel Mowry'	,	'Son Alice Mowry'	,	''	,	''	,	'M'	,	1794	,	1882	,	88	);
INSERT INTO tblCorpse VALUES(	102	,	'Polly'	,	'Mowry'	,	'Wife of Thomas Mowry'	,	'Daughter of Hannah Giles'	,	'Daughter of John Giles'	,	'N'	,	'F'	,	1755	,	1812	,	57	);
INSERT INTO tblCorpse VALUES(	103	,	'Thomas'	,	'Mowry'	,	'Son Daniel Mowry'	,	'Son of Alice Mowry'	,	''	,	'N'	,	'M'	,	1786	,	1872	,	86	);
INSERT INTO tblCorpse VALUES(	104	,	'Martha'	,	'Mowry'	,	'Daughter of Thomas Mowry'	,	'Daughter of Martha Harris Mowry'	,	''	,	'N'	,	'F'	,	1818	,	1899	,	81	);
INSERT INTO tblCorpse VALUES(	105	,	'Phebe '	,	'Mowry-Smith'	,	'Son of George M'	,	''	,	''	,	'N'	,	'F'	,	1819	,	1842	,	22	);
INSERT INTO tblCorpse VALUES(	106	,	'Alice'	,	'Mowry'	,	''	,	''	,	''	,	'N'	,	'F'	,	1814	,	1836	,	21	);
INSERT INTO tblCorpse VALUES(	107	,	'Wilson'	,	'Mowry'	,	''	,	''	,	''	,	'N'	,	'M'	,	1810	,	1824	,	13	);
INSERT INTO tblCorpse VALUES(	108	,	'Reuben '	,	'Mowry'	,	''	,	''	,	''	,	'N'	,	'M'	,	1821	,	1838	,	16	);
INSERT INTO tblCorpse VALUES(	109	,	'Amey'	,	'Mowry'	,	'Daughter of Daniel Mowry'	,	'Daughter of Alce Mowry'	,	''	,	'N'	,	'F'	,	1782	,	1863	,	80	);
INSERT INTO tblCorpse VALUES(	110	,	'Samuel'	,	'Mowry'	,	'Son of Alce Mowry'	,	'Son of Daniel Mowry'	,	'Brother of Mary mowry'	,	'N'	,	'M'	,	1775	,	1799	,	24	);
INSERT INTO tblCorpse VALUES(	111	,	'Mary'	,	'Mowry'	,	'Daughter of Daniel Mowry'	,	'Daughter of Alce Mowry'	,	'Sister of samuel Mowry'	,	'N'	,	'F'	,	1776	,	1806	,	30	);
INSERT INTO tblCorpse VALUES(	112	,	'Phebe '	,	'Mowry'	,	'Wife of Reuben Mowry'	,	''	,	''	,	'N'	,	'F'	,	1784	,	1873	,	88	);
INSERT INTO tblCorpse VALUES(	113	,	'Reuben '	,	'Mowry'	,	''	,	''	,	''	,	'N'	,	'M'	,	1778	,	1852	,	73	);
INSERT INTO tblCorpse VALUES(	114	,	'Roger W.'	,	'Mowry'	,	'Son of Jabez W Mowry'	,	'Son of Susan MJ Mowry'	,	''	,	'N'	,	'M'	,	1860	,	1882	,	22	);
INSERT INTO tblCorpse VALUES(	115	,	'Daniel S.'	,	'Mowry'	,	''	,	''	,	''	,	'N'	,	'M'	,	1850	,	1851	,	1	);
INSERT INTO tblCorpse VALUES(	116	,	'Jabez W. '	,	'Mowry'	,	'son of Reuben Mowry'	,	'Son of Phebe'	,	''	,	'Y'	,	'M'	,	1824	,	1898	,	74	);
INSERT INTO tblCorpse VALUES(	117	,	'Susan'	,	'Mowry'	,	'Daughter of Jeremiah Mowry'	,	'Daughter of Betsy Mowry'	,	''	,	'N'	,	'F'	,	1834	,	1882	,	48	);
INSERT INTO tblCorpse VALUES(	118	,	'Susanna'	,	'Mowry'	,	'wife of Daniel Mowry jr'	,	'daughter of Elisha Sicere'	,	'Daughter of Amy Sicere'	,	'N'	,	'F'	,	1761	,	1850	,	89	);
INSERT INTO tblCorpse VALUES(	119	,	'Alce'	,	'Mowry'	,	'wife of Daniel Mowry jr'	,	'daughter of Samuel Aldrich'	,	'daughter of Priscilla Aldrich'	,	'N'	,	'F'	,	1751	,	1806	,	55	);
INSERT INTO tblCorpse VALUES(	120	,	'Sara'	,	'Mowry'	,	'Daughter of Sydney'	,	'Daughter of Bertha'	,	'Sister of Eva'	,	'N'	,	'F'	,	1882	,	1919	,	37	);
INSERT INTO tblCorpse VALUES(	121	,	'Eva'	,	'Mowry'	,	'Daughter of Sydney'	,	'Daughter of Bertha'	,	'Sister of Eva'	,	'N'	,	'F'	,	1877	,	1879	,	1	);
INSERT INTO tblCorpse VALUES(	122	,	'Arabella'	,	'Mowry'	,	'wife of abraham mowry'	,	''	,	''	,	'N'	,	'F'	,	1857	,	1939	,	82	);
INSERT INTO tblCorpse VALUES(	123	,	'Abraham'	,	'Mowry'	,	'husbandof arabella'	,	''	,	''	,	'N'	,	'M'	,	1863	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	124	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	125	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	126	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	127	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	128	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	129	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	130	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	131	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	132	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	133	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	134	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	135	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	136	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	137	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	138	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	139	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	140	,	'Delia'	,	'Baxter'	,	'Daughter of John Baxter'	,	'Daughter of Thankful Baxter'	,	''	,	'N'	,	'F'	,	1806	,	1844	,	38	);
INSERT INTO tblCorpse VALUES(	141	,	'Thankful'	,	'Baxter'	,	'Wife of john WC Baxter'	,	'Daughter of Daniel Mowry'	,	'Daughter of Alce Mowry'	,	'N'	,	'F'	,	1780	,	1821	,	41	);
INSERT INTO tblCorpse VALUES(	142	,	'John'	,	'Baxter'	,	''	,	''	,	''	,	'N'	,	'M'	,	1802	,	1833	,	31	);
INSERT INTO tblCorpse VALUES(	143	,	'Charles'	,	'Appleton'	,	'Son of Christopher Appleton'	,	'Son of Elizabeth Appleton'	,	''	,	'N'	,	'M'	,	1812	,	1852	,	40	);
INSERT INTO tblCorpse VALUES(	144	,	'Amey'	,	'Appleton'	,	'Daughter of JWC baxter'	,	'Daughter of Thankful Baxter'	,	''	,	'N'	,	'F'	,	1812	,	1874	,	62	);
INSERT INTO tblCorpse VALUES(	145	,	'Emma'	,	'Appleton'	,	''	,	''	,	''	,	'N'	,	'F'	,	Null	,	1852	,	Null	);
INSERT INTO tblCorpse VALUES(	146	,	'Susanna Caroline'	,	'Mowry'	,	'Daughter of Gideon Mowry'	,	'Daughter of Amy Mowry'	,	''	,	'N'	,	'F'	,	1824	,	1825	,	1	);
INSERT INTO tblCorpse VALUES(	147	,	'Amey'	,	'Mowry'	,	'Wife of Gideon Mowry'	,	'Daughter of Jonathan Angell'	,	''	,	'N'	,	'F'	,	1790	,	1842	,	52	);
INSERT INTO tblCorpse VALUES(	148	,	'Gideon '	,	'Mowry'	,	''	,	''	,	''	,	'N'	,	'M'	,	1784	,	1865	,	81	);
INSERT INTO tblCorpse VALUES(	149	,	'Helen'	,	'Patience'	,	'Daughter of John Mowry'	,	'Daughter of Almira Mowry'	,	''	,	'N'	,	'F'	,	1847	,	1874	,	27	);
INSERT INTO tblCorpse VALUES(	150	,	'Alphonso'	,	'Mowry'	,	'Son of John Mowry'	,	'Son of Almira Mowry'	,	''	,	'N'	,	'M'	,	1845	,	1848	,	3	);
INSERT INTO tblCorpse VALUES(	151	,	'Emory'	,	'Mowry'	,	'Son of John Mowry'	,	'Son of Almira Mowry'	,	''	,	'N'	,	'M'	,	1840	,	1842	,	2	);
INSERT INTO tblCorpse VALUES(	152	,	'Eliza'	,	'Mowry'	,	''	,	''	,	''	,	'N'	,	'F'	,	1831	,	1832	,	1	);
INSERT INTO tblCorpse VALUES(	153	,	'Edward'	,	'Mowry'	,	'Son of Sylvester Mowry'	,	'Son Patience Mowry'	,	''	,	'N'	,	'M'	,	1740	,	1801	,	61	);
INSERT INTO tblCorpse VALUES(	154	,	'Waity'	,	'Mowry'	,	'Daughter of Sylvester Mowry'	,	'Daughter of Patience Mowry'	,	''	,	'N'	,	'F'	,	1790	,	1871	,	81	);
INSERT INTO tblCorpse VALUES(	155	,	'Marcia'	,	'Jencks'	,	'Wife of Elisha M Jencks'	,	'Daughter of Sylvester Mowry'	,	'Daughter of Patience Mowry'	,	'N'	,	'F'	,	1803	,	1884	,	81	);
INSERT INTO tblCorpse VALUES(	156	,	'John'	,	'Mowry'	,	'Son of Sylvester Mowry'	,	'Son Patience Mowry'	,	''	,	'N'	,	'M'	,	1806	,	1876	,	70	);
INSERT INTO tblCorpse VALUES(	157	,	'Almira'	,	'Smith'	,	'Wife of John A Mowry'	,	'Daughter of Alfred Smith'	,	'Daughterof Eliza Smith'	,	'N'	,	'F'	,	1807	,	1891	,	84	);
INSERT INTO tblCorpse VALUES(	158	,	'Sylvester'	,	'Mowry'	,	'Son of Elisha Mowry'	,	'Son of Phebe Mowry'	,	''	,	'N'	,	'M'	,	1768	,	1851	,	83	);
INSERT INTO tblCorpse VALUES(	159	,	'Patience'	,	'Mowry'	,	'Wife of Sylvester Mowry'	,	'Daughter of Wlliam Cook'	,	'Daughter of Ruth Cook'	,	'N'	,	'F'	,	1764	,	1845	,	81	);
INSERT INTO tblCorpse VALUES(	160	,	'William'	,	'Mowry'	,	'Son of Sylvester Mowry'	,	'Son Patience Mowry'	,	''	,	'N'	,	'M'	,	1808	,	1830	,	22	);
INSERT INTO tblCorpse VALUES(	161	,	'Phebe'	,	'Mowry'	,	'Daughter of Sylvester Mowry'	,	'Daughter of Patience Mowry'	,	''	,	'N'	,	'F'	,	1806	,	1826	,	20	);
INSERT INTO tblCorpse VALUES(	162	,	'Mary'	,	'Mowry'	,	'Daughter of Sylvester Mowry'	,	'Daughter of Patience Mowry'	,	''	,	'N'	,	'F'	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	163	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	164	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	165	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	166	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	167	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	168	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	169	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	170	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	171	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	172	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	173	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	174	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	175	,	'Alice'	,	'Mowry'	,	'Daughter of Lamech c Mowry'	,	''	,	''	,	'N'	,	'F'	,	Null	,	1868	,	Null	);
INSERT INTO tblCorpse VALUES(	176	,	'Lamech C'	,	'Mowry'	,	''	,	''	,	''	,	'N'	,	'M'	,	1807	,	1880	,	73	);
INSERT INTO tblCorpse VALUES(	177	,	'Unknown'	,	'Mowry'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	1818	,	Null	);
INSERT INTO tblCorpse VALUES(	178	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	179	,	'Unknown'	,	'Unknown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	180	,	'Unkown'	,	'Unkown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	181	,	'Unknown'	,	'Dorcas'	,	'Wife of Lewis Place'	,	''	,	''	,	'N'	,	'F'	,	Null	,	1813	,	Null	);
INSERT INTO tblCorpse VALUES(	182	,	'Unkown'	,	'Unkown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	183	,	'Unkown'	,	'Unkown'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	184	,	'Mary F.'	,	'VialL'	,	'Daughter of James Viall'	,	'Daughter of Linda Viall'	,	''	,	'N'	,	'F'	,	1846	,	1857	,	11	);
INSERT INTO tblCorpse VALUES(	185	,	'James'	,	'M.'	,	''	,	''	,	''	,	'N'	,	'M'	,	Null	,	1835	,	23	);
INSERT INTO tblCorpse VALUES(	186	,	'Lydia'	,	'Mowry'	,	''	,	''	,	''	,	'N'	,	'F'	,	Null	,	1831	,	Null	);
INSERT INTO tblCorpse VALUES(	187	,	'Anna'	,	'Mowry'	,	'Daughter of James Viall'	,	'Daughter of Linda Viall'	,	''	,	'N'	,	'F'	,	Null	,	1844	,	Null	);
INSERT INTO tblCorpse VALUES(	188	,	'A. M.'	,	'Mowry'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	189	,	'U. G.'	,	'Mowry'	,	''	,	''	,	''	,	'N'	,	''	,	Null	,	Null	,	Null	);
INSERT INTO tblCorpse VALUES(	190	,	'Bertha D.'	,	'Mowry'	,	'Wife of Sydney'	,	'Father of Eva '	,	'Father of Sara'	,	'N'	,	'F'	,	1847	,	1910	,	63	);
INSERT INTO tblCorpse VALUES(	191	,	'Sidney H.'	,	'Mowry'	,	'Husband of Bertha'	,	'Father of Eva '	,	'Father of Sara'	,	'N'	,	'F'	,	1847	,	1930	,	83	);
INSERT INTO tblCorpse VALUES(	192	,	'Anne'	,	'Mowry'	,	'Wife of Daniel Mowry II'	,	'Daughter of Michael Phillips'	,	'Daughter of Anne Phillips'	,	'N'	,	'F'	,	1721	,	1751	,	30	);
INSERT INTO tblCorpse VALUES(	193	,	'Daniel '	,	'Mowry I'	,	'Son of Daniel Mowry'	,	'Son of Mary Mowry'	,	''	,	'Y'	,	'M'	,	1729	,	1806	,	76	);
INSERT INTO tblCorpse VALUES(	194	,	'Daniel'	,	'Mowry II'	,	'Son of N/a'	,	''	,	''	,	'Y'	,	'M'	,	1789	,	1869	,	80	);

INSERT INTO tblGraveCorpse VALUES(	101	,	1	);
INSERT INTO tblGraveCorpse VALUES(	102	,	2	);
INSERT INTO tblGraveCorpse VALUES(	103	,	3	);
INSERT INTO tblGraveCorpse VALUES(	104	,	4	);
INSERT INTO tblGraveCorpse VALUES(	105	,	5	);
INSERT INTO tblGraveCorpse VALUES(	106	,	6	);
INSERT INTO tblGraveCorpse VALUES(	107	,	7	);
INSERT INTO tblGraveCorpse VALUES(	108	,	8	);
INSERT INTO tblGraveCorpse VALUES(	109	,	9	);
INSERT INTO tblGraveCorpse VALUES(	110	,	10	);
INSERT INTO tblGraveCorpse VALUES(	111	,	11	);
INSERT INTO tblGraveCorpse VALUES(	112	,	12	);
INSERT INTO tblGraveCorpse VALUES(	113	,	13	);
INSERT INTO tblGraveCorpse VALUES(	114	,	14	);
INSERT INTO tblGraveCorpse VALUES(	115	,	15	);
INSERT INTO tblGraveCorpse VALUES(	116	,	16	);
INSERT INTO tblGraveCorpse VALUES(	117	,	17	);
INSERT INTO tblGraveCorpse VALUES(	118	,	18	);
INSERT INTO tblGraveCorpse VALUES(	119	,	19	);
INSERT INTO tblGraveCorpse VALUES(	120	,	20	);
INSERT INTO tblGraveCorpse VALUES(	121	,	21	);
INSERT INTO tblGraveCorpse VALUES(	122	,	22	);
INSERT INTO tblGraveCorpse VALUES(	123	,	22	);
INSERT INTO tblGraveCorpse VALUES(	124	,	23	);
INSERT INTO tblGraveCorpse VALUES(	125	,	24	);
INSERT INTO tblGraveCorpse VALUES(	126	,	25	);
INSERT INTO tblGraveCorpse VALUES(	127	,	26	);
INSERT INTO tblGraveCorpse VALUES(	128	,	27	);
INSERT INTO tblGraveCorpse VALUES(	129	,	28	);
INSERT INTO tblGraveCorpse VALUES(	130	,	29	);
INSERT INTO tblGraveCorpse VALUES(	131	,	30	);
INSERT INTO tblGraveCorpse VALUES(	132	,	31	);
INSERT INTO tblGraveCorpse VALUES(	133	,	32	);
INSERT INTO tblGraveCorpse VALUES(	134	,	33	);
INSERT INTO tblGraveCorpse VALUES(	135	,	34	);
INSERT INTO tblGraveCorpse VALUES(	136	,	35	);
INSERT INTO tblGraveCorpse VALUES(	137	,	36	);
INSERT INTO tblGraveCorpse VALUES(	138	,	37	);
INSERT INTO tblGraveCorpse VALUES(	139	,	38	);
INSERT INTO tblGraveCorpse VALUES(	140	,	39	);
INSERT INTO tblGraveCorpse VALUES(	141	,	40	);
INSERT INTO tblGraveCorpse VALUES(	142	,	40	);
INSERT INTO tblGraveCorpse VALUES(	143	,	41	);
INSERT INTO tblGraveCorpse VALUES(	144	,	42	);
INSERT INTO tblGraveCorpse VALUES(	145	,	43	);
INSERT INTO tblGraveCorpse VALUES(	146	,	44	);
INSERT INTO tblGraveCorpse VALUES(	147	,	45	);
INSERT INTO tblGraveCorpse VALUES(	148	,	46	);
INSERT INTO tblGraveCorpse VALUES(	149	,	47	);
INSERT INTO tblGraveCorpse VALUES(	150	,	48	);
INSERT INTO tblGraveCorpse VALUES(	151	,	49	);
INSERT INTO tblGraveCorpse VALUES(	152	,	50	);
INSERT INTO tblGraveCorpse VALUES(	153	,	51	);
INSERT INTO tblGraveCorpse VALUES(	154	,	52	);
INSERT INTO tblGraveCorpse VALUES(	155	,	53	);
INSERT INTO tblGraveCorpse VALUES(	156	,	54	);
INSERT INTO tblGraveCorpse VALUES(	157	,	55	);
INSERT INTO tblGraveCorpse VALUES(	158	,	56	);
INSERT INTO tblGraveCorpse VALUES(	159	,	57	);
INSERT INTO tblGraveCorpse VALUES(	160	,	58	);
INSERT INTO tblGraveCorpse VALUES(	161	,	59	);
INSERT INTO tblGraveCorpse VALUES(	162	,	60	);
INSERT INTO tblGraveCorpse VALUES(	163	,	61	);
INSERT INTO tblGraveCorpse VALUES(	164	,	62	);
INSERT INTO tblGraveCorpse VALUES(	165	,	63	);
INSERT INTO tblGraveCorpse VALUES(	166	,	64	);
INSERT INTO tblGraveCorpse VALUES(	167	,	65	);
INSERT INTO tblGraveCorpse VALUES(	168	,	66	);
INSERT INTO tblGraveCorpse VALUES(	169	,	67	);
INSERT INTO tblGraveCorpse VALUES(	170	,	68	);
INSERT INTO tblGraveCorpse VALUES(	171	,	69	);
INSERT INTO tblGraveCorpse VALUES(	172	,	70	);
INSERT INTO tblGraveCorpse VALUES(	173	,	71	);
INSERT INTO tblGraveCorpse VALUES(	174	,	72	);
INSERT INTO tblGraveCorpse VALUES(	175	,	73	);
INSERT INTO tblGraveCorpse VALUES(	176	,	74	);
INSERT INTO tblGraveCorpse VALUES(	177	,	75	);
INSERT INTO tblGraveCorpse VALUES(	178	,	76	);
INSERT INTO tblGraveCorpse VALUES(	179	,	77	);
INSERT INTO tblGraveCorpse VALUES(	180	,	78	);
INSERT INTO tblGraveCorpse VALUES(	181	,	79	);
INSERT INTO tblGraveCorpse VALUES(	182	,	80	);
INSERT INTO tblGraveCorpse VALUES(	183	,	81	);
INSERT INTO tblGraveCorpse VALUES(	184	,	82	);
INSERT INTO tblGraveCorpse VALUES(	185	,	83	);
INSERT INTO tblGraveCorpse VALUES(	186	,	84	);
INSERT INTO tblGraveCorpse VALUES(	187	,	85	);
INSERT INTO tblGraveCorpse VALUES(	188	,	86	);
INSERT INTO tblGraveCorpse VALUES(	189	,	87	);
INSERT INTO tblGraveCorpse VALUES(	190	,	88	);
INSERT INTO tblGraveCorpse VALUES(	191	,	89	);
INSERT INTO tblGraveCorpse VALUES(	192	,	90	);
INSERT INTO tblGraveCorpse VALUES(	193	,	91	);
INSERT INTO tblGraveCorpse VALUES(	194	,	92	);

INSERT INTO tblWar VALUES(1, "Revolutionary War");
INSERT INTO tblWar VALUES(2, "Civil War");

Insert INTO tblcorpsewar VALUES(116,2);
Insert INTO tblcorpsewar VALUES(193,1);
Insert INTO tblcorpsewar VALUES(194,2);
